name: setup wasmtime e2e tests
on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 19
      
      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run package
        env:
          NODE_OPTIONS: --openssl-legacy-provider

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup-wasmtime
          path: dist/wasmtime/setup/index.js

  setup-default-wasmtime:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: setup-wasmtime
          path: dist/wasmtime/setup/

      - name: setup wasmtime
        uses: ./wasmtime/setup/
        with:
          github_token: ${{ github.token }}

      - name: verify wasmtime setup
        run: wasmtime --version

  setup-specific-wasmtime-version:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve saved Github action
        uses: actions/download-artifact@v3
        with:
          name: setup-wasmtime
          path: dist/wasmtime/setup/

      - name: setup wasmtime
        uses: ./wasmtime/setup/
        with:
          version: "v12.0.0"
          github_token: ${{ github.token }}

      - name: wasmtime setup successful
        if: ${{ contains(env.WASMTIME_VERSION, '12.0.0') }}
        run: echo "wasmtime setup successful"

      - name: wasmtime setup failed
        if: ${{ !contains(env.WASMTIME_VERSION, '12.0.0') }}
        run: |
          echo "expected version: 12.0.0, found: ${{ env.WASMTIME_VERSION }}"
          exit 1
